### ISSUE TITLE
Bem-vindos ao início do desenvolvimento da iaraCLI!

### ISSUE THREAD

**Issue by mdcg** [sigmages/iaraCLI#1]
Fala, pessoal. Criei a primeira issue aqui do nosso repositório para estabelecer o que a iaraCLI é e o que ela não é.

Numa concepção inicial, ela possui a seguinte funcionalidade: Ser um CLI para notificar serviços de mensageria (Telegram, Slack, Google Chats, Discord, Whatsapp, etc) através de seus respectivos webhooks. Um dos diferenciais dela, inicialmente, é poder notificar mais de um serviço simultaneamente. Para ficar melhor explicado, imaginem a execução do seguinte comando:

```
iara --notify="slack,telegram,whastapp" --message="Domo arigato, Mr. Roboto" --type="info"
```

Nos respectivos serviços, teriámos uma mensagem mais ou menos assim: :robot: `INFO: Domo arigato, Mr. Roboto`.

Eu sei.. É algo super simples. Mas como eu disse, é apenas uma concepção inicial. Gostaria de ouvir um pouco das sugestões dos senhores sobre como deixar essa CLI mais interessante. Funcionalidades, campos de atuação, tecnologias, arquitetura, o que vocês quiserem tratar aqui será muito bem-vindo. Agradeço a atenção de todos e aguardo o contato de vocês!

**Comment by Ronald-TR** [comment]
Um ótimo ponto! Eu acredito que um foco realmente útil para o iaraCLI seja a característica de um HUB. receber N triggers e disparar a notificação para N destinos. Ele pode também ser declarativo (chamou, notificou) como uma segunda idéia.

Um ótimo exemplo para seguirmos com a ideia do HUB é a modelagem [desse projeto](https://github.com/open-telemetry/opentelemetry-python-contrib), mais especificamente esse manifesto:
```yaml
receivers:    
  postgres:     
    <table name>:
        <trigger event statement>
  sns:
    <http url>
  prometheus:
     ...
  
exporters:
  slack:
     <...>
  chats:
     <...>
  telegram:
     <...>
  discord:
    <...>
service:
  pipelines:
    notify:
      receivers: [postgres, sns, prometheus]
      exporters: [slack, chats, telegram, discord]
```
O manifesto acima é só uma ideia, mas já demonstra a natureza e o potencial do iaraCLI.
